### PR TITLE
add "http:" if streams data URL is missing it

### PR DESCRIPTION
**Pull request by wong-fei-hung**
This should hopefully fix the breakage reported here.

I only tested it on "6:30PM News" variety show.

https://www.reddit.com/r/Addons4Kodi/comments/zlgo1q/icdrama_not_working_dec_12_2022/

### CODE REVIEW

**Comment by soraxas** [comment]
Thanks!

Should it be adding `https`? (or whatever protocol the current Web request is using)

**Comment by decantur** [comment]
I get a dependency failure when attempting to install 2.3.2.

Is the resolveurl version number correct?  I am unable to locate that version number.  

Thanks

**Comment by wong-fei-hung** [comment]
> I get a dependency failure when attempting to install 2.3.2.
> 
> Is the resolveurl version number correct? I am unable to locate that version number.
> 
> Thanks

If you are using gujal00's version and the repo update is lagging behind, you can get the zip manually here: https://github.com/Gujal00/smrzips/tree/master/zips/script.module.resolveurl

**Comment by wong-fei-hung** [comment]
> Thanks!
> 
> Should it be adding `https`? (or whatever protocol the current Web request is using)

I'm not sure if `[ 'adrama.to', 'icdrama.se', 'icdrama.to']` even supports HTTPS? I didn't spend too much time on this and the functions seem too specialized and trouble than it's worth to make it use a protocol argument? Also stuff like `self.get_url()` also hardcodes in use of `http://`

Reports from other people in the reddit post seem to indicate this works for them.

**Comment by soraxas** [comment]
Sounds good to me

**Pull request merged**
