### PR TITLE
Update hdplay.py

### PR DESCRIPTION
**Pull request by DoubleAsterisks**
Python 2-3 compatible : f-string alternative

### CODE REVIEW

**Comment by soraxas** [comment]
Why? I don't think the current addon version supports python 3.

**Comment by DoubleAsterisks** [comment]
I was trying to run this addon on a older version of Kodi that uses python 2.

f-string was not available before python 3.6.

Sorry, you disregard this pull request.

**Comment by soraxas** [comment]
I'm confused, this fork is for Kodi Matrix (19), which doesn't even supports Python 2?

**Comment by DoubleAsterisks** [comment]
yes, my mistake. please disregard this request

**Pull request closed without merging**
