### PR TITLE
ResolveURL 5.1.67 refactor compatibility

### PR DESCRIPTION
**Pull request by AndyA4**
From the [main thread](https://github.com/aznhusband/aznhusband.github.io/pull/55#issuecomment-1142289879)

### CODE REVIEW

**Comment by soraxas** [comment]
Thank you Andy for the PR

**Comment by xalagaco** [comment]
When can we expect to see 2.3.1 released?

**Comment by soraxas** [comment]
Can you verify that it works? I wasn't able to verify it at the moment as the kodi on my linux system is having some issue

**Comment by xalagaco** [comment]
I'd be happy to try, but where is it?

**Comment by soraxas** [comment]
Try this one: [test-build.zip](https://github.com/soraxas/aznhusband.github.io/files/8962403/test-build.zip)

**Comment by xalagaco** [comment]
Confirmed HLS links work with ResolveURL 5.1.70 on Windows Kodi 19.4.

**Comment by soraxas** [comment]
Okay thanks @xalagaco !

**Comment by cdkao** [comment]
Once again, thank you everyone for keeping this alive. I hope you all stay safe and well!

**Pull request merged**
